### PR TITLE
Switch to updated container & drop duplicated functionality

### PR DESCRIPTION
**Pull request by ypcs**
Until now many features were duplicated in Vagrant vs. other environments. This patchset drops lots of that functionality from the box itself, and moves it into container that shares lots of features with production and other environments.

All scripts that get executed by `Vagrantfile` in seravo/wordpress repository have been replaced with non-operational ones, that do nothing. Instead we rely on misc scripts inside the container that execute things, like WP installation, dumping and loading database contents etc.

### CODE REVIEW

**Comment by ypcs** [comment]
Note: container still needs some improvements and fixes before this can be rolled out. However, changes in this repository are complete now, and can be reviewed.

While waiting for improvements in container, you can test these changes, just remember that you'll just get Vagrant box that starts container, but without functional container.

**Comment by ypcs** [comment]
Notable changes:

 - if you create `.nodocker` file in your `wordpress` project directory, you'll get access to Vagrant itself (instead of getting forwarded to container)
 - if you create `.seravo_autoupdate` file in your `wordpress` project directory, box gets updated at each startup (= use bleeding-edge container version)

**Comment by ottok** [comment]
LGTM based on reading the code. Have not tested anything yet.

About naming:
- Call the tool inside the Vagrant box that manages the container simply 'sc' (for Seravo Controller)
- Call the .nodocker instead .seravo-controller-shell
- Call the .seravo_autoupdate instead .seravo-controller-autoupdate

**Comment by ypcs** [comment]
Renames done, each in separate commit (ac660c8, f2ab086, 59ab989), can be squashed to bbdb360.

**Pull request merged**
