### PR TITLE
Update container handling

### PR DESCRIPTION
**Pull request by ypcs**
Update how VM handles the Docker container.

 - add little delay to Docker start, so that Vagrant has done it's mounts before Docker tries to mount /data
 - use flag file `~/.nodocker` for decision making: `vagrant ssh` enters the VM if file exists (create using `vagrant ssh -c "touch .nodocker"`)
 - use SSH for container access instead of `docker exec`, this allows forwarding SSH agent (you may access the container with `vagrant ssh` or `ssh wordpress.local`)
 - add port forward for xdebug (9000:9000) from Docker to host VM
 - also, add missing MOTD

### CODE REVIEW

**Comment by ottok** [comment]
```
TASK [docker : install docker python bindings] *********************************
fatal: [default]: FAILED! => {"changed": false, "cmd": "/usr/bin/pip2 install docker-py", "failed": true, "msg": "stdout: Collecting docker-py\n\n:stderr: Exception:\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/pip/basecommand.py\", line 209, in main\n    status = self.run(options, args)\n  File \"/usr/lib/python2.7/dist-packages/pip/commands/install.py\", line 328, in run\n    wb.build(autobuilding=True)\n  File \"/usr/lib/python2.7/dist-packages/pip/wheel.py\", line 748, in build\n    self.requirement_set.prepare_files(self.finder)\n  File \"/usr/lib/python2.7/dist-packages/pip/req/req_set.py\", line 360, in prepare_files\n    ignore_dependencies=self.ignore_dependencies))\n  File \"/usr/lib/python2.7/dist-packages/pip/req/req_set.py\", line 512, in _prepare_file\n    finder, self.upgrade, require_hashes)\n  File \"/usr/lib/python2.7/dist-packages/pip/req/req_install.py\", line 273, in populate_link\n    self.link = finder.find_requirement(self, upgrade)\n  File \"/usr/lib/python2.7/dist-packages/pip/index.py\", line 442, in find_requirement\n    all_candidates = self.find_all_candidates(req.name)\n  File \"/usr/lib/python2.7/dist-packages/pip/index.py\", line 400, in find_all_candidates\n    for page in self._get_pages(url_locations, project_name):\n  File \"/usr/lib/python2.7/dist-packages/pip/index.py\", line 545, in _get_pages\n    page = self._get_page(location)\n  File \"/usr/lib/python2.7/dist-packages/pip/index.py\", line 648, in _get_page\n    return HTMLPage.get_page(link, session=self.session)\n  File \"/usr/lib/python2.7/dist-packages/pip/index.py\", line 757, in get_page\n    \"Cache-Control\": \"max-age=600\",\n  File \"/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py\", line 480, in get\n    return self.request('GET', url, **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/pip/download.py\", line 378, in request\n    return super(PipSession, self).request(method, url, *args, **kwargs)\n  File \"/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py\", line 468, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py\", line 576, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/adapter.py\", line 46, in send\n    resp = super(CacheControlAdapter, self).send(request, **kw)\n  File \"/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/adapters.py\", line 376, in send\n    timeout=timeout\n  File \"/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py\", line 610, in urlopen\n    _stacktrace=sys.exc_info()[2])\n  File \"/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/retry.py\", line 228, in increment\n    total -= 1\nTypeError: unsupported operand type(s) for -=: 'Retry' and 'int'\n"}

$ vagrant ssh
...
vagrant@seravo-wordpress:~$ pip2 install docker-py
Traceback (most recent call last):
  File "/usr/bin/pip2", line 9, in <module>
    load_entry_point('pip==8.1.1', 'console_scripts', 'pip2')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by ypcs** [comment]
@l3ku can you test building this? I can't repeat error described above.

Note: this branch might not be compatible with previous checkout, so it might be feasible to remove existing branch & checking out latest version.

**Comment by l3ku** [comment]
Sure, going to test this now.

**Comment by l3ku** [comment]
Couldn't reproduce the Ansible error mentioned above:
```
TASK [docker : install docker python bindings] *********************************
changed: [default]
```
### Notices during vagrant up
- Some exception is thrown from node modules:
```
wordpress-box: Error: Timeout
wordpress-box:     at Timeout._onTimeout (/usr/lib/node_modules/wait-on/lib/wait-on.js:92:10)
wordpress-box:     at ontimeout (timers.js:386:14)
wordpress-box:     at tryOnTimeout (timers.js:250:5)
wordpress-box:     at Timer.listOnTimeout (timers.js:214:5)
```
- Activation of git hooks is asked two times, and the following errors are faced:
  - "Inappropriate ioctl for device"
  - "The remote command "wp-restart-nginx &> /dev/null" returned a failed exit..."
```
Generating autoload files
> WordPress\Installer::symlinkWPContent
==> wordpress-box: Executing remote command "wp core is-installed --quiet &>/dev/null || wp-vagrant-import-db"...
==> wordpress-box: mesg: ttyname failed: Inappropriate ioctl for device
==> wordpress-box: entering site container... /usr/local/bin/wp-vagrant-import-db
==> wordpress-box: |----------------------------------------------------------------------------|
==> wordpress-box: | Welcome to Seravo.com!                                                     |
==> wordpress-box: | Unauthorized use is forbidden. All connections are monitored and recorded. |
==> wordpress-box: |----------------------------------------------------------------------------|
==> wordpress-box: Success: Database was imported correctly!
==> wordpress-box: Remote command execution finished.
    wordpress-box: Activate git hooks in scripts/hooks? (yes): no
    wordpress-box: Activate git hooks in scripts/hooks? (yes): no
==> wordpress-box: Executing remote command "wp-use-asset-proxy &> /dev/null"...
==> wordpress-box: Remote command execution finished.
==> wordpress-box: Executing remote command "wp-restart-nginx &> /dev/null"...
==> wordpress-box: Remote command execution finished.
The remote command "wp-restart-nginx &> /dev/null" returned a failed exit
code or an exception. The error output is shown below:
```
### In Docker
The file directory seems intact with WordPress installed, but nginx is not working properly. Restarting nginx also does not work: 
```
root@vagrant:~/htdocs# wp-restart-nginx
testing nginx configuration...
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
checking for php backends...
Found PHP mode definition: php7 in 'php7'
PHP7(.0) mode enabled
Restarting nginx...
Error: Timeout
    at Timeout._onTimeout (/usr/lib/node_modules/wait-on/lib/wait-on.js:92:10)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by ypcs** [comment]
It seems that there was invalid port configuration for nginx, which caused wait-on timeouts. This is now fixe in the container, so everything should now work as expected. (No changes needed to this PR.)

I'm waiting for more test results :)

**Comment by ottok** [comment]
## Test results 2018-05-21

First `vagrant up` ended with SSH connection failure:
```
...
==> wordpress-box: entering site container... /usr/local/bin/wp-generate-ssl
==> wordpress-box: ssh_exchange_identification: Connection closed by remote host
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Second `vagrant up` however continued to the end but accessing the server didn't work:
```
$ curl -iL https://wordpress.local/
curl: (7) Failed to connect to wordpress.local port 443: Connection refused
```

Nginx or logs inside the container did not show any errors. I don't have time to look deeper right now..

**Comment by ottok** [comment]
Tested now with an existing project, and `vagrant up` fails with:
```
$ vagrant up
Bringing machine 'wordpress-box' up with 'virtualbox' provider...
==> wordpress-box: Clearing any previously set forwarded ports...
==> wordpress-box: Clearing any previously set network interfaces...
==> wordpress-box: Preparing network interfaces based on configuration...
    wordpress-box: Adapter 1: nat
    wordpress-box: Adapter 2: hostonly
==> wordpress-box: Forwarding ports...
    wordpress-box: 22 (guest) => 2222 (host) (adapter 1)
==> wordpress-box: Running 'pre-boot' VM customizations...
==> wordpress-box: Booting VM...
==> wordpress-box: Waiting for machine to boot. This may take a few minutes...
    wordpress-box: SSH address: 127.0.0.1:2222
    wordpress-box: SSH username: vagrant
    wordpress-box: SSH auth method: private key
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
    wordpress-box: Warning: Authentication failure. Retrying...
^C==> wordpress-box: Waiting for cleanup before exiting...
Vagrant exited after cleanup due to external interrupt.
```

I assume this is nothing we can do. When customers start using a new Vagrant image, they need to run `vagrant destroy` first so I think.

**Comment by ypcs** [comment]
Branch has now been updated. Image has been published at https://app.vagrantup.com/seravo/boxes/wordpress-beta .

**Comment by ypcs** [comment]
All previous and currently known issues have been resolved. Latest commits (4cad1fe, d0468a7) introduce rewritten Docker container handling. Now container gets re-created always at virtual machine boot.

**Pull request merged**
